### ISSUE TITLE
Question about authentification

### ISSUE THREAD

**Issue by kecinzer** [ventz/openconnect-gui-menu-bar#2]
First I want to thank you for nice tool for openconnect.
I have question about connection password and PINs.
To connect to my VPN I need to provide username, password and then PIN and after that second PIN that I recieve via SMS.
It's possible to store first PIN also in keychain, so when I want to connect, I only wait for SMS with second PIN?

**Comment by ventz** [comment]
@kecinzer I am glad you are finding this useful.

There are two ways you can do this:
1.) The easier - the password (no matter how many components) gets sent as a single string.
For example, let's say you have: "password-here" "pin#1" "sms", it gets presented as "password-herepin#1sms". So, with that in mind, you can add your first pin to the password in your keychain (same item)

2.) The "harder" (not by much) - you can create a second item in the keychain, let's say your vpn is "something.domain.tld", you can create an entry called "something.domain.tld-PIN"

For "Keychain Item Name" and "Account Name" use the value for "$VPN_HOST"-PIN and "VPN_PIN" respectively

That said, I would just go with the 1st solution :)

**Comment by kecinzer** [comment]
Thank you for answer, but your script doesn't work for me at all. I must doing something wrong.

**Comment by ventz** [comment]
@kecinzer Did you set the `PUSH_OR_PIN=` to *not* push?

Also - are you connecting to a Cisco AnyConnect?

**Comment by kecinzer** [comment]
I tried it with Terminal for debbuging, but I can see only command and nothing happend no matter what I set for PUSH_OR_PIN variable.
When I connecting manualy I use parametr --user and then openconnect ask me for password. After I put it it ask me about second password (PIN), then SMS arrive and I can write Response...

Here is example. I use something instead of my work name and not providing real IP adressess.

sudo openconnect --user=reznicekpet vpn.something.cz/adm
POST https://vpn.something.cz/adm
Connected to xx.xxx.xx.xxx:443
SSL negotiation with vpn.something.cz
Connected to HTTPS on vpn.something.cz
XML POST enabled
Please enter your username and password.
Password:
Password:
POST https://vpn.something.cz/

Wait for token to change,
then enter the new tokencode:
Response:
POST https://vpn.something.cz/
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connected as xx.xxx.xx.xxx, using SSL
Established DTLS connection (using GnuTLS). Ciphersuite (DTLS0.9)-(RSA)-(AES-128-CBC)-(SHA1).
Connect Banner:

**Comment by ventz** [comment]
@kecinzer Get it to work from the CLI (that is, just via openconnect) for your VPN server in a one line/single shot (including your password + pin + token), and we can take a look at what is different in terms of the way it plugs into the UI side.

If I am understanding this correctly, this is the equivalent of 2FA with a rotating OTP. I am not sure about the "wait for the token to change", but it also sounds like they might have this in place so that you don't submit one on the "edge" of it rotating out.

**Comment by kecinzer** [comment]
I can't get it to work at one line or shot. Because after I write password and PIN, then I receive generated SMS with another PIN (I don't know or I don't have this PIN before I send my static one). That is:
Wait for token to change,
then enter the new tokencode:
Response:

I can connect different way, that instead of waiting for SMS, I can add PIN from my HW RSA token thats changing every few seconds. But I used to SMS authetication because I don't need to bring HW RSA token with me.

**Comment by ventz** [comment]
So that's a different problem :)

It might be worth reaching out to the openconnect community/mailing list to see if there's a way to input the 2nd token somehow in a programmatic way.

From the GUI perspective here - once you have a "clean" way of inputting that, you could add a prompt for it (same as for pin currently), and that would work. But you definitely need a way to cleanly input this into openconnect.
