### ISSUE TITLE
debugging

### ISSUE THREAD

**Issue by carmineyiu** [ventz/openconnect-gui-menu-bar#4]
I echo the following openconnect command and run it in terminal find it run ok. 
sudo "$VPN_EXECUTABLE" -u "$VPN_USERNAME" -i "$VPN_INTERFACE" "$VPN_HOST" 
But echo password, it accept, but when i add VIP response code it fail
------Extract from command line ------------
SSL negotiation with xxx.xxx.com
Connected to HTTPS on xxx.xxx.com
XML POST enabled
Please enter your username and password.
Password:
POST https://xxxx.xxxx.com/
Enter Your VIP Security Code:
Response:
fgets (stdin): Inappropriate ioctl for device 

---------------------------
what is the parameter for push/pin or other item?

**Comment by ventz** [comment]
@carmineyiu For the push vs pin -- it really comes down to:

1.) Are you using Duo? If so - then you have the option of push (default) or PIN
vs
2.) If you are NOT using Duo -- it's assumed that you will enter a pin by default, in which case the name is just the friendly "pop-up" name. So you can enter something like:
`PUSH_OR_PIN="VIP Security Code"`

As far as any other failure/the command -- make sure you can just connect via openconnect since this is essentially a GUI applet around it. Once open connect works, then map out the options back into the "gui".

**Comment by carmineyiu** [comment]
Thanks, it resolve, I do know know the sudo visudo command, so take me time to find out. 
Also I try to add echo for debug, unfortunately it is not working. I find there is a comment "debug" at the bottom of script, which provide me some insight..
