### ISSUE TITLE
add route

### ISSUE THREAD

**Issue by carmineyiu** [ventz/openconnect-gui-menu-bar#5]
I have two VPN (one cisco anynet + openconnect) online in the sametimes. The issue is when openconnect successfully connect to VPN host, route may not add success to route table. Ping will success for few second, then will be overwrite/refreshed by cisco anynet, and pind cannot connect to VPN host. 
Is it possible to check the connection to an VPN host for few second, if it is not cannot connect to a specific address, then retry?

**Comment by ventz** [comment]
@carmineyiu This is a question for the openconnect community :)

You can set any command you want behind the UI -- anything that openconnect supports will work here, but it sounds like you have larger problems on your side that you want to track down. If openconnect connects perfectly/sets the routes, it should never overwrite your routes unless you have a subnet/IP space collision. If that's the case, you simply cannot have those two VPNs together, no matter what clients you use. (if that is the case, and you control one of them, change the subnet if possible). Also, try migrating your cisco anyconnect (assuming that's what you meant) to openconnect -- there's really no reason to use cisco's. Again, you really should figure out what is causing anyconnect to overwrite the routes because it seems like there is a bigger routing issue going on.
